version: '3'

services:
  java-app:
    build:
      context: .
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - mysql
    environment: # we can take these env variables from .env file
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=grocery_db
      - DB_PORT=3306

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grocery_db
    ports:
      - 3306:3306
